[tool.poetry]
name = "seminar-sample"
version = "0.1.0"
description = ""
authors = ["たまみ <tama@subthread.co.jp>"]
license = "UNLICENSED"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.14,<4.0"
django = "^6.0.6"
psycopg = "^3.3.4"
redis = "^8.0.1"
boto3 = "^1.43.36"
django-storages = "^1.14.6"
google-api-python-client = "^2.198.0"
pillow = "^12.2.0"


[tool.poetry.group.dev.dependencies]
black = "^26.5.1"
isort = "^8.0.1"
pyproject-flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119

[tool.isort]
profile = "black"
line_length = 119

[tool.flake8]
max-line-length = 119
extend-ignore = [
    "E203", # ":"の前の空白を入れないルール
    "W503", # 演算子の前に改行しないようにするルール
    "E501", # black かけても line too long になるところはしかたない
    "W291", # black かけても trailing whitespace になるのはおそらく文字列のなか
    "E722", # エラーはすべて補足したい
]
exclude = [
    "__pycache__",
    "migrations",
]
per-file-ignores = [
    '*/__init__.py:F401,F403',
    'src/project/settings/docker.py,src/project/settings/ecs.py:F401,F403,F405',
]
