# Generated by Django 5.0.1 on 2024-01-25 15:38
from django.core.files.storage import storages
from django.db import migrations

import app.common.utils.file
import app.common.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceuser",
            name="icon_url",
        ),
        migrations.AddField(
            model_name="serviceuser",
            name="icon",
            field=app.common.fields.file.ImageFileField(
                blank=True,
                help_text="10.0\xa0MB以内の画像ファイル（PNG/JPEG）を指定してください。",
                null=True,
                storage=storages["resource"],
                upload_to=app.common.utils.file.upload_to,
                validators=[app.common.utils.validators.MaxFileSizeValueValidator(10485760)],
                verbose_name="アイコン",
            ),
        ),
    ]
