# Generated by Django 5.0.1 on 2024-03-09 07:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.localtime, editable=False, verbose_name="登録日時"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                ("name", models.CharField(verbose_name="名前")),
            ],
            options={
                "verbose_name": "著者",
                "verbose_name_plural": "著者",
                "db_table": "author",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.localtime, editable=False, verbose_name="登録日時"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                ("name", models.CharField(verbose_name="名前")),
            ],
            options={
                "verbose_name": "出版社",
                "verbose_name_plural": "出版社",
                "db_table": "publisher",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Bibliographic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.localtime, editable=False, verbose_name="登録日時"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                ("title", models.CharField(verbose_name="タイトル")),
                ("published_at", models.DateField(blank=True, null=True, verbose_name="発行日")),
                ("authors", models.ManyToManyField(blank=True, to="readlog.author", verbose_name="著者")),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="readlog.publisher",
                        verbose_name="出版社",
                    ),
                ),
            ],
            options={
                "verbose_name": "書誌情報",
                "verbose_name_plural": "書誌情報",
                "db_table": "bibliographic",
                "ordering": ("title", "publisher__name"),
            },
        ),
    ]
