# Generated by Django 5.0.1 on 2024-03-09 07:42
from django.core.files.storage import storages
from django.db import migrations, models

import app.common.fields.file
import app.common.utils.file


class Migration(migrations.Migration):
    dependencies = [
        ("readlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibliographic",
            name="picture",
            field=app.common.fields.file.ImageFileField(
                blank=True,
                null=True,
                storage=storages["resource"],
                upload_to=app.common.utils.file.upload_to,
                verbose_name="書影",
            ),
        ),
        migrations.AddField(
            model_name="bibliographic",
            name="sample",
            field=models.FileField(
                blank=True,
                help_text="立ち読みサンプルPDFなどがあれば登録してください",
                null=True,
                storage=storages["resource"],
                upload_to=app.common.utils.file.upload_to,
                verbose_name="サンプル",
            ),
        ),
    ]
