# Generated by Django 5.0.1 on 2024-03-12 15:32

import django.utils.timezone
from django.core.files.storage import storages
from django.db import migrations, models

import app.common.utils.file
import app.readlog.models.importer


class Migration(migrations.Migration):
    dependencies = [
        ("readlog", "0003_readlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBibliographic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, editable=False, verbose_name="アップロード日時"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                ("import_at", models.DateTimeField(null=True, verbose_name="インポート日時")),
                (
                    "file",
                    app.readlog.models.importer.ImportFileField(
                        storage=storages["import_file"],
                        upload_to=app.common.utils.file.upload_to,
                        verbose_name="ファイル",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="備考メモ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "プレビュー中"),
                            ("in_progress", "インポート中"),
                            ("complete", "インポート完了"),
                            ("error", "エラー終了"),
                            ("cancel", "キャンセル"),
                        ],
                        default="-",
                        verbose_name="ステータス",
                    ),
                ),
                ("count", models.IntegerField(null=True, verbose_name="登録・更新数")),
                ("result", models.TextField(null=True, verbose_name="結果")),
                ("error", models.TextField(null=True, verbose_name="エラー")),
            ],
            options={
                "verbose_name": "インポートファイル",
                "verbose_name_plural": "インポートファイル",
                "db_table": "import_bibliographic",
                "ordering": ("-created_at",),
            },
        ),
    ]
