# Generated by Django 5.0.1 on 2024-03-12 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivitySummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_date", models.DateField(verbose_name="対象日")),
                ("steps", models.IntegerField(blank=True, null=True, verbose_name="歩数")),
                ("sleep_time", models.FloatField(blank=True, null=True, verbose_name="睡眠時間")),
                (
                    "gymnastics",
                    models.CharField(
                        blank=True, choices=[("done", "した"), ("not", "しなかった")], null=True, verbose_name="アクティブ体操"
                    ),
                ),
                (
                    "dental",
                    models.CharField(
                        blank=True, choices=[("done", "した"), ("not", "しなかった")], null=True, verbose_name="歯磨き"
                    ),
                ),
                (
                    "morning",
                    models.CharField(
                        blank=True, choices=[("eat", "食べた"), ("not", "食べなかった")], null=True, verbose_name="朝食"
                    ),
                ),
                (
                    "snack",
                    models.CharField(
                        blank=True, choices=[("eat", "食べた"), ("not", "食べなかった")], null=True, verbose_name="間食"
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="メモ")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="ユーザー"
                    ),
                ),
            ],
            options={
                "verbose_name": "活動記録",
                "verbose_name_plural": "活動記録",
                "db_table": "activity_summary",
            },
        ),
        migrations.CreateModel(
            name="ActivityDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity", models.CharField(verbose_name="運動内容")),
                ("minutes", models.IntegerField(blank=True, null=True, verbose_name="運動時間")),
                ("mets", models.FloatField(blank=True, null=True, verbose_name="運動強度METs")),
                ("details", models.TextField(blank=True, null=True, verbose_name="詳細")),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="activity.activitysummary",
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "運動",
                "verbose_name_plural": "運動",
                "db_table": "activity",
            },
        ),
    ]
