# Generated by Django 5.0.1 on 2024-03-12 07:43

import django.utils.timezone
from django.core.files.storage import storages
from django.db import migrations, models

import app.common.utils.file


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityArchive",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.localtime, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "archive_period",
                    models.CharField(
                        choices=[("weekly", "週次"), ("monthly", "月次"), ("annual", "年次")], verbose_name="アーカイブ期間"
                    ),
                ),
                ("start_period", models.DateField(verbose_name="対象期間：開始日")),
                ("end_period", models.DateField(verbose_name="対象期間：終了日")),
                (
                    "archive",
                    models.FileField(
                        storage=storages["archive"],
                        upload_to=app.common.utils.file.upload_to,
                        verbose_name="アーカイブ",
                    ),
                ),
                ("filesize", models.IntegerField(null=True, verbose_name="ファイルサイズ")),
                ("note", models.TextField(blank=True, default="", verbose_name="備考")),
            ],
            options={
                "verbose_name": "アーカイブ",
                "verbose_name_plural": "アーカイブ",
                "db_table": "activity_archive",
            },
        ),
    ]
