name: Setup
on:
  workflow_call:
    inputs:
      poetry-command:
        required: true
        type: string

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install packages
        run: poetry install --no-interaction
      - name: Run check
        run: poetry run ${{inputs.poetry-command}} src/
